export const FETCH_COLLECTIONS_YEARS = "FETCH_COLLECTIONS_YEARS"
export const FETCH_COLLECTIONS_YEARS_SUCCESS = "FETCH_COLLECTIONS_YEARS_SUCCESS"
export const FETCH_COLLECTIONS_YEARS_FAILED = "FETCH_COLLECTIONS_YEARS_FAILED"
export const FETCH_COLLECTIONS_YEARS_OLD_DATA = "FETCH_COLLECTIONS_YEARS_OLD_DATA"


export const getCollectionsByYears = ( callback ) => ({
    type: FETCH_COLLECTIONS_YEARS,
    callback
})

